//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LEATS_Project.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Administrator
    {
        
        public int AdministratorID { get; set; }
        [Required]
        public string Id { get; set; }
        [Required]
        [Display(Name ="First Name")]
        public string FirstName { get; set; }
        [Required]
        [Display(Name = "Last Name")]
        public string LastName { get; set; }
        [Required]
        public string Gender { get; set; }
        [Required]
        public string Ethnicity { get; set; }
        [Required]
        [Display(Name = "Date of Birth")]
        public System.DateTime DateOfBirth { get; set; }
        [Required]
        [Display(Name = "Cell No.")]
        public string CellphoneNo { get; set; }
        [Required]
        public string Email { get; set; }
        [Required]
        [Display(Name = "Street Name")]
        public string StreetName { get; set; }
        [Required]
        public string Suburb { get; set; }
        [Required]
        public string City { get; set; }
        [Required]
        public string Province { get; set; }
        [Required]
        [Display(Name = "Postal Code")]
        public int PostalCode { get; set; }
        [Required]
        [Display(Name = "Profile Picture")]
        public byte[] ProfilePicture { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
