//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LEATS_Project.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Appointment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Appointment()
        {
            this.Payments = new HashSet<Payment>();
            this.Reviews = new HashSet<Review>();
        }
    
        public int AppointmentID { get; set; }
        public int StudentD { get; set; }
        public int TutorID { get; set; }
        public System.DateTime RequestTime { get; set; }
        [Required]
        public string AppointmentTime { get; set; }
        [Required]
        public int AppointmentDuration { get; set; }
        [Required]
        public string AppointmentType { get; set; }
        [Required]
        public string AppointmentStatus { get; set; }
        [Required]
        public string AppointmentDetails { get; set; }
        [Required]
        public string Location { get; set; }
    
        public virtual Student Student { get; set; }
        public virtual Tutor Tutor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Payment> Payments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Review> Reviews { get; set; }
        public virtual Student Student1 { get; set; }
    }
}
