//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LEATS_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ModuleApplication
    {
        public int ModuleApplicationID { get; set; }
        public int TutorID { get; set; }
        public string ModuleCode { get; set; }
        public string ModuleName { get; set; }
        public System.DateTime Date { get; set; }
        public string Status { get; set; }
    
        public virtual Tutor Tutor { get; set; }
    }
}
