//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LEATS_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ModuleRequest
    {
        public int RequestID { get; set; }
        public int StudentID { get; set; }
        public string ModuleCode { get; set; }
        public string ModuleName { get; set; }
        public System.DateTime RequestDate { get; set; }
    
        public virtual Student Student { get; set; }
    }
}
