//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LEATS_Project.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Payment
    {
        public int PaymentID { get; set; }
        public int AppointmentID { get; set; }
        public int StudentID { get; set; }
        public decimal Amount { get; set; }
        [Display(Name = "Payment Type")]
        public string PaymentType { get; set; }
        public System.DateTime Date { get; set; }
        public string Status { get; set; }
    
        public virtual Appointment Appointment { get; set; }
    }
}
