//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LEATS_Project.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TutorApplication
    {
        public int ApplicationID { get; set; }
        [Required]
        public int StudentID { get; set; }
        [Required]
        [Display(Name = "Module Code")]
        public string ModuleCode { get; set; }
        [Required]
        [Display(Name = "Module Name")]
        public string ModuleName { get; set; }
        [Display(Name = "Academic Transcript")]
        public byte[] AcademicTranscript { get; set; }
        [Display(Name = "Proof Of Registration")]
        public byte[] ProofOfRegistration { get; set; }
        [Display(Name = "Application Date")]
        public System.DateTime ApplicationDate { get; set; }
        [Display(Name = "Status")]
        public string ApplicationStatus { get; set; }
        public virtual Student Student { get; set; }
    }
}
